services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: promoguard
      POSTGRES_USER: promoguard
      POSTGRES_PASSWORD: promoguard
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
